// Auto-generated by Stellar ZK Kit. DO NOT EDIT BY HAND.
// Typed client for the ProofOfFundsVerifier Soroban contract.

export interface ProofOfFundsInputs {
  min: bigint;
}

export interface ProofBundle {
  /** Hex-encoded proof_blob = [count(4B LE)][pubs][proof]. */
  proofBlob: string;
  /** Hex-encoded ordered public input field elements (32 bytes each). */
  publicInputs: string[];
}

/** Canonical declared order of public inputs for proof_of_funds. */
export const ProofOfFundsInputOrder: ReadonlyArray<keyof ProofOfFundsInputs> = [
  "min",
] as const;

function toFieldElement(value: bigint): Uint8Array {
  const out = new Uint8Array(32);
  let v = value;
  for (let i = 31; i >= 0 && v > 0n; i--) {
    out[i] = Number(v & 0xffn);
    v >>= 8n;
  }
  return out;
}

function toHex(bytes: Uint8Array): string {
  let s = "";
  for (const b of bytes) s += b.toString(16).padStart(2, "0");
  return s;
}

/**
 * Encodes a bb proof + ordered public inputs into
 * proof_blob = [count(4B LE)][pubs (32B each)][proof].
 */
export function encodeForSoroban(
  proof: Uint8Array,
  publicInputs: bigint[]
): ProofBundle {
  const fields = publicInputs.map(toFieldElement);
  const count = fields.length;
  const header = new Uint8Array(4);
  header[0] = count & 0xff;
  header[1] = (count >> 8) & 0xff;
  header[2] = (count >> 16) & 0xff;
  header[3] = (count >> 24) & 0xff;

  const total = 4 + fields.length * 32 + proof.length;
  const blob = new Uint8Array(total);
  let offset = 0;
  blob.set(header, offset);
  offset += 4;
  for (const f of fields) {
    blob.set(f, offset);
    offset += 32;
  }
  blob.set(proof, offset);

  return {
    proofBlob: toHex(blob),
    publicInputs: fields.map(toHex),
  };
}
