// Auto-generated by Stellar ZK Kit.
// Keep this null until a real transaction has been verified for this circuit.
export interface OnChainEvidence {
  network: string;
  contractId: string;
  transactionHash: string;
  ledger: number;
  confirmedAt: string;
  explorerUrl: string;
}

export const ON_CHAIN_EVIDENCE: OnChainEvidence | null = {
  network: "Stellar Testnet",
  contractId: "CAKL7ZRKWCGYGII4FF4EZND2XHBI6IUOR77W7AGE3VKYXHUJSEPIGQKB",
  transactionHash: "9acc98a09320f4a8242d50bddae49e7ab79c4d0b67319f3486362eb769a82446",
  ledger: 3375063,
  confirmedAt: "2026-07-01 07:13:33 UTC",
  explorerUrl:
    "https://stellar.expert/explorer/testnet/tx/9acc98a09320f4a8242d50bddae49e7ab79c4d0b67319f3486362eb769a82446",
};
